import csv
import sys

'''
Code to add an index column entry to every row in a file
We needed to do this in order for the MapReduce algorithm
for generating pairs to work

Usage: python3 add_index.py <vectors file generated by "correct_complete_vectors.py">
'''

rows = []

def add_index(file_name):
    with open(file_name) as f:
        f.readline()
        reader = csv.reader(f)
        counter = 0
        for line in reader:
            line = [counter] + line
            rows.append(line)
            counter += 1

    with open("{}_indexes.csv".format(file[:-3]),'w') as f:
        writer = csv.writer(f)
        writer.writerows(rows)

if __name__ == "__main___":
    add_index(sys.argv[1])
